<font size=5>**脑区水平相关**

In [1]:
%reset -f
import pandas as pd
AgeDf = pd.read_csv(r"D:\research\HCP_parcellation_Lsym-AVR\CamCan\KRR parcel size to age\Weights\All nets weights.csv")
AgeDf

,currNetPfm1,currNetPfm2,currNetPfm3,currNetPfm4,currNetPfm5,currNetPfm6,currNetPfm7,currNetPfm8,currNetPfm9,currNetPfm10,...,currNetPfm91,currNetPfm92,currNetPfm93,currNetPfm94,currNetPfm95,currNetPfm96,currNetPfm97,currNetPfm98,currNetPfm99,currNetPfm100
0,-0.001881,-0.002029,-0.001640,-0.001781,-0.001789,-0.001893,-0.001841,-0.001899,-0.002125,-0.001613,...,-0.001656,-0.001930,-0.001919,-0.001964,-0.001823,-0.001859,-0.002247,-0.001823,-0.001645,-0.002087
1,0.448204,0.455435,0.457945,0.454576,0.457253,0.453194,0.457967,0.457353,0.456384,0.447497,...,0.449991,0.452165,0.455277,0.453335,0.453477,0.454536,0.449719,0.459177,0.456167,0.459110
2,-0.332384,-0.340501,-0.347024,-0.330445,-0.332700,-0.336770,-0.327031,-0.333166,-0.302226,-0.373553,...,-0.335521,-0.362083,-0.341524,-0.350182,-0.328425,-0.321783,-0.324598,-0.344049,-0.358564,-0.309262
3,-0.390496,-0.378820,-0.380706,-0.380574,-0.380683,-0.393438,-0.395309,-0.378421,-0.419843,-0.350650,...,-0.376245,-0.374034,-0.382614,-0.377545,-0.395504,-0.387651,-0.400632,-0.372704,-0.360481,-0.406921
4,-1.537217,-1.531195,-1.509119,-1.513632,-1.521850,-1.540328,-1.550037,-1.544766,-1.577898,-1.488161,...,-1.517009,-1.526022,-1.530485,-1.516729,-1.567509,-1.528122,-1.557468,-1.536211,-1.496146,-1.586399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
331,-1.759030,-1.778925,-1.761927,-1.764490,-1.773651,-1.784080,-1.796956,-1.788633,-1.821680,-1.725873,...,-1.769648,-1.773073,-1.761732,-1.752196,-1.783644,-1.781919,-1.793898,-1.761886,-1.746741,-1.795527
332,0.237516,0.229916,0.231958,0.232793,0.231203,0.239505,0.236868,0.240636,0.242561,0.229912,...,0.238277,0.234358,0.235368,0.234343,0.232909,0.240316,0.246730,0.236288,0.227669,0.243112
333,4.109718,4.030818,4.009604,4.021785,4.008718,4.061573,4.079795,4.055359,4.202160,3.917797,...,4.030571,4.011893,4.031427,3.984156,4.059324,4.115126,4.081507,3.985479,3.917058,4.150709
334,-5.617153,-5.516427,-5.490235,-5.489477,-5.511548,-5.533395,-5.571155,-5.554364,-5.770727,-5.348683,...,-5.529640,-5.468197,-5.489877,-5.435337,-5.607500,-5.550263,-5.608929,-5.538044,-5.350384,-5.678298
335,2.192964,2.144762,2.149344,2.103272,2.160267,2.137923,2.152405,2.148664,2.228633,2.071292,...,2.164997,2.134906,2.140565,2.124652,2.203864,2.098851,2.183781,2.216180,2.097428,2.209953

In [ ]:
MeanWeightsMap = AgeDf.mean(axis=1)
MeanWeightsMap

In [3]:
AllMeanWeights = pd.DataFrame()
AllMeanWeights['Age'] = MeanWeightsMap
AllMeanWeights

          Age
0   -0.001862
1    0.452949
2   -0.334907
3   -0.384685
4   -1.527662
..        ...
331 -1.769181
332  0.235508
333  4.043137
334 -5.521674
335  2.144950

[336 rows x 1 columns]

In [ ]:
# Load cognitive task data
cogTasks = ['Fluid intelligence','Emotion expression recognition','PicturePriming','Face recognition','FamousFaces','Motor learning']
for ct in cogTasks:
    currTaskDf = pd.read_csv(rf'D:\research\HCP_parcellation_Lsym-AVR\CamCan\KRR parcel size to cognition\weights\results/{ct}/All nets weights.csv')
    MeanWeightsMap = currTaskDf.mean(axis=1)
    AllMeanWeights[ct] = MeanWeightsMap
AllMeanWeights['Motor learning'] = -AllMeanWeights['Motor learning']
AllMeanWeights

,Age,Fluid intelligence,Emotion expression recognition,PicturePriming,Face recognition,FamousFaces,Motor learning
0,-0.001862,0.003274,0.002753,0.002821,0.002035,0.001677,0.004592
1,0.452949,-0.604747,-0.372850,-0.445224,-0.425221,-0.144239,-0.564703
2,-0.334907,-1.316712,1.240204,-0.422182,0.250485,-0.367029,-2.450613
3,-0.384685,1.423970,0.233046,0.750089,0.583144,0.604076,2.041576
4,-1.527662,1.915731,1.532662,1.042499,0.749125,0.818924,0.805113
...,...,...,...,...,...,...,...
331,-1.769181,2.287417,0.817293,2.183110,1.554604,2.671131,2.543623
332,0.235508,-0.344280,-0.174038,-0.369481,-0.170682,-0.489250,-0.162185
333,4.043137,-9.102880,-3.358026,-7.362574,-8.385259,-8.455331,-13.153638
334,-5.521674,10.444110,5.441228,10.195939,10.161556,10.596857,15.860449
335,2.144950,-2.822188,-2.984580,-4.164999,-3.639564,-3.788736,-4.918703

In [8]:
import seaborn as sns
import matplotlib.pyplot as plt
WeightCorr = AllMeanWeights.corr()
WeightCorrMasked = WeightCorr.copy().iloc[1:,:-1]

In [ ]:
import numpy as np
plt.rcParams['font.family'] = ['Times New Roman','SimSun']
# plt.rcParams['font.sans-serif'][0]='Arial'
# print(plt.rcParams['font.sans-serif'])
# Create lower triangular matrix
mask = np.triu(np.ones_like(WeightCorrMasked, dtype=bool),1)
# np.fill_diagonal(mask, True)
fig , ax = plt.subplots(figsize =(3,2.7),dpi=300)
# colormap = sns.diverging_palette(220, 10, as_cmap = True)
colormap = sns.color_palette("vlag", as_cmap = True)
YTickNames = ['Gf','EER','PPR','FR','FF','ML']
XTickNames = ['Age','Gf','EER','PPR','FR','FF']
_ = sns.heatmap(
    WeightCorrMasked,
    xticklabels=XTickNames,
    yticklabels=YTickNames,
    cmap = colormap,
    square=True, 
    cbar_kws={'shrink':.85}, 
    ax=ax,
    annot=True, 
    linewidths=0.1,vmax=0.98, linecolor='white',
    annot_kws={'fontsize':7 },
    mask=mask
)
# ax.set_xticklabels(ax.get_xticklabels(),rotation=0,rotation_mode='anchor',ha = 'right',va='center',fontsize=7)
ax.set_yticklabels(ax.get_yticklabels(),rotation=0)
ax.tick_params(axis='both',labelsize=7,length=3,width=1)
cbar=ax.collections[0].colorbar
cbar.ax.tick_params(axis='y',length=0,labelsize = 7,pad=2)
cbar.set_ticks([WeightCorrMasked.min().min(),0.98])
# plt.title('Correlation of weights on parcel level',size=9)
plt.savefig('Parcel level weights heatmap.svg',format='svg')

<font size=5>**核团水平相关**</font>

In [9]:
import numpy as np
AgeDf = pd.read_csv(r"D:\research\HCP_parcellation_Lsym-AVR\CamCan\KRR parcel size to age\Weights\All nets nucbynet mean mat.csv",index_col=0)
AgeWeightsVec = np.array(AgeDf)
AgeWeightsVec = AgeWeightsVec.flatten()
index = [f'{y}_{x}' for x in AgeDf.index for y in AgeDf.columns]
NucLevelWeights = pd.DataFrame(index=index)
NucLevelWeights['Age'] = AgeWeightsVec

In [ ]:
# Replication of each cognitive task
cogTasks = ['Fluid intelligence','Emotion expression recognition','PicturePriming','Face recognition','FamousFaces','Motor learning']
for ct in cogTasks:
    CurrDf = pd.read_csv(f"results/{ct}/All nets nucbynet mean mat.csv",index_col=0)
    CurrWeightsVec = np.array(CurrDf)
    CurrWeightsVec = CurrWeightsVec.flatten()
    NucLevelWeights[ct] = CurrWeightsVec
NucLevelWeights['Motor learning']*=-1

In [ ]:
# Create lower triangular matrix
mask = np.triu(np.ones_like(NucLevelWeights.corr(), dtype=bool))
np.fill_diagonal(mask, True)
_ , ax = plt.subplots(figsize =(7, 6),dpi=600)
colormap = sns.diverging_palette(220, 10, as_cmap = True)

YTickNames = ['','Fluid intelligence','Emotion recognition','Picture priming','Face recognition','Famous faces','Motor learning']
XTickNames = ['Age','Fluid intelligence','Emotion recognition','Picture priming','Face recognition','Famous faces']
_ = sns.heatmap(
    NucLevelWeights.corr(),
    xticklabels=XTickNames,
    yticklabels=YTickNames,
    cmap = colormap,
    square=True, 
    cbar_kws={'shrink':.9 }, 
    ax=ax,
    annot=True, 
    linewidths=0.1,vmax=1.0, linecolor='white',
    annot_kws={'fontsize':12 },
    mask=mask
)
ax.set_xticklabels(ax.get_xticklabels(),rotation=45,rotation_mode='anchor',ha = 'right',va='center')
plt.title('Pearson Correlation of Weights in Nuclei Level', y=1.05, size=15)
plt.savefig('figure/Nuclei level weights corr.pdf',format='pdf')

<font size=5>**Age和FI的散点图改**

In [14]:
from scipy.stats import pearsonr

In [ ]:
# Brain region level
ParcelAge2MlDf = AllMeanWeights[['Age','Fluid intelligence']]
r,p = pearsonr(ParcelAge2MlDf['Age'], ParcelAge2MlDf['Fluid intelligence'])
plt.figure(figsize=(3,2.7),dpi = 300)
sns.regplot(x=ParcelAge2MlDf['Age'],y=ParcelAge2MlDf['Fluid intelligence'],scatter_kws={"color":"purple","s": 5,"zorder":0,'edgecolor':'none'},line_kws={"color":"blue","lw": 1,"zorder":1})
# plt.title('Parcel level weights', size=9)
if p>=0.0001:
    text = f"r = {r:.3f}\np = {p:.3e}"  # Format: 3 decimal places, scientific notation
else:
    text = f"r = {r:.3f}\np < 0.0001"
ax=plt.gca()
ax.text(
    x=0.75, y=0.95,  # Position parameters (relative coordinates, 0~1)
    s=text,
    transform=ax.transAxes,  # Key parameter: use relative coordinate system
    fontsize=7,
    color='black',
    va='top',  # Vertical alignment
    ha='left',  # Horizontal alignment
    bbox=dict(facecolor='white', alpha=0.8, edgecolor='none')  # Background box
)
ax = plt.gca()
ax.xaxis.label.set_size(7)
ax.yaxis.label.set_size(7)
ax.set_xlabel('Age prediction model weights', size=7)
ax.set_ylabel('Gf prediction model weights', size=7)
ax.spines['bottom'].set_linewidth(1)
ax.spines['left'].set_linewidth(1)
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.tick_params(axis='both',width=1,length = 3,labelsize=7)
plt.savefig('Parcel level weights scatter.svg', format='svg')

In [ ]:
NucAge2MlDf = NucLevelWeights[['Age','Fluid intelligence']]
NucAge2MlDf['Nucleus'] = [NucAge2MlDf.index.str.split("_",expand=True)[i][1] for i in range(len(NucAge2MlDf.index))]

In [ ]:
NucAge2MlDf = NucLevelWeights[['Age','Fluid intelligence']]
NucAge2MlDf['Nucleus'] = [NucAge2MlDf.index.str.split("_",expand=True)[i][1] for i in range(len(NucAge2MlDf.index))]
r,p = pearsonr(NucAge2MlDf['Age'],NucAge2MlDf['Fluid intelligence'])
plt.figure(figsize=(6,5),dpi = 300)
sns.regplot(x=NucAge2MlDf['Age'],y=NucAge2MlDf['Fluid intelligence'],scatter=False,line_kws={"color":"blue","lw": 2, "zorder": 1})
sns.scatterplot(x=NucAge2MlDf['Age'],y=NucAge2MlDf['Fluid intelligence'],hue=NucAge2MlDf['Nucleus'],zorder=2)
plt.title('Nuclei Level Weights', size=15)
ax = plt.gca()
if p>=0.0001:
    text = f"r = {r:.3f}\np = {p:.3e}"  # Format: 3 decimal places, scientific notation
else:
    text = f"r = {r:.3f}\np < 0.0001"
ax.text(
    x=0.75, y=0.95,  # Position parameters (relative coordinates, 0~1)
    s=text,
    transform=ax.transAxes,  # Key parameter: use relative coordinate system
    fontsize=12,
    color='black',
    va='top',  # Vertical alignment
    ha='left',  # Horizontal alignment
    bbox=dict(facecolor='white', alpha=0.8, edgecolor='none')  # Background box
)
ax.xaxis.label.set_size(12)
ax.yaxis.label.set_size(12)
ax.spines['bottom'].set_linewidth(2)
ax.spines['left'].set_linewidth(2)
ax.spines['right'].set_visible(False)
ax.spines['top'].set_visible(False)
ax.tick_params(axis='both',width=2,length = 5)